backend:
  name: git-gateway
  repo: ahanshaw/eleventy-portfolio
  branch: main
media_folder: "_site/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "intro"
    label: "Intro"
    files:
      - file: "_data/intro.json"
        label: "Intro Content"
        name: "introContent"
        fields:
          - { label: "Background Image", name: "hero", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Intro", name: "copy", widget: "markdown" }
  - name: "work"
    label: "Work"
    widget: "object"
    files:
      - file: "_data/work.json"
        label: "Projects"
        name: "project"
        widget: "list"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "markdown",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Image", name: "image", widget: "image", required: false }
          - {
              label: "Image Alt Text",
              name: "alt",
              widget: "string",
              required: false,
            }
          - { label: "PDF", name: "pdf", widget: "file", required: false }
